#ifndef TAFL_VARIANTS_H
#define TAFL_VARIANTS_H

#define E 0x00
#define W 0x01
#define B 0x02
#define K 0x04

#define SELECTED 8
#define VALID_MOVE 16
#define LAST_MOVE 32
#define FLAG_MASK (SELECTED | VALID_MOVE | LAST_MOVE)

#define BLACK_MASK B
#define WHITE_MASK (W | K)
#define PIECE_MASK (BLACK_MASK | WHITE_MASK)

#define TABLUT_SIZE 9
#define BRANDUBH_SIZE 7
#define GWDDBWYLL_SIZE 7
#define FIDCHELL_SIZE 7
#define ARD_RI_SIZE 7
#define EALDFAEDER_SIZE 9
#define TAWLBWRDD_SIZE 11
#define TAWLBWRDD_ALT_SIZE 11
#define TAWLBWRDD_ALT_2_SIZE 11
#define HNEFATAFL_SIZE 11
#define LARGE_HNEFATAFL_SIZE 13
#define ALEA_EVANGELII_SIZE 19


enum Variant{
	Brandubh,
	Gwddbwyll,
	Fidchell,
	Ard_Ri,
	Tablut,
	Tawlbwrdd,
	Tawlbwrdd_Alternate,
	Tawlbwrdd_Alternate_2,
	Hnefatafl,
	Large_Hnefatafl,
	Alea_Evangelii
};

const int BRANDUBH[BRANDUBH_SIZE][BRANDUBH_SIZE];
const int GWDDBWYLL[GWDDBWYLL_SIZE][GWDDBWYLL_SIZE];
const int FIDCHELL[FIDCHELL_SIZE][FIDCHELL_SIZE];
const int ARD_RI[ARD_RI_SIZE][ARD_RI_SIZE];
const int TABLUT[TABLUT_SIZE][TABLUT_SIZE];
const int TAWLBWRDD[TAWLBWRDD_SIZE][TAWLBWRDD_SIZE];
const int TAWLBWRDD_ALTERNATE[TAWLBWRDD_ALT_SIZE][TAWLBWRDD_ALT_SIZE];
const int TAWLBWRDD_ALTERNATE_2[TAWLBWRDD_ALT_2_SIZE][TAWLBWRDD_ALT_2_SIZE];
const int HNEFATAFL[HNEFATAFL_SIZE][HNEFATAFL_SIZE];
const int LARGE_HNEFATAFL[LARGE_HNEFATAFL_SIZE][LARGE_HNEFATAFL_SIZE];
const int ALEA_EVANGELII[ALEA_EVANGELII_SIZE][ALEA_EVANGELII_SIZE];

#endif
